### ISSUE TITLE
Speedberry Prematurely Spawning in Bissy's Int

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#106]
Linj loaded into a normal save and found the speedberry loaded in Bissy's intermediate, despite not previously beating it. The silver was not loaded at the time.
Submitted by Bissy

**Comment by maddie480** [comment]
Fixed in https://github.com/EverestAPI/CelesteCollabUtils2/commit/9de6adfb796bc9d5d84ee5869e6e7b12d836f064
