### ISSUE TITLE
Space Jam Fever Dream last cutscene alt path

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#109]
The last text box on the alt path is not skippable (not sure if thats intended or not) and there is also a frame (maybe more) where you can pause and it says skip cutscene, but pressing it doesnt actually do anything https://clips.twitch.tv/RichPrettiestSrirachaNotATK
Submitted by Marlin

**Comment by bissy-bissy-bissy** [comment]
Cruor has said they don't care enough to look into this, and since it's not a major issue it'll stay unresolved
