### ISSUE TITLE
Tiles in Claustrophobia have flashing

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#110]
https://discordapp.com/channels/403698615446536203/429775260108324865/754534988304875560
Submitted by Bissy

**Comment by bissy-bissy-bissy** [comment]
While this is not something we can fix, we decided this shouldn't be a *huge* accessibility issue as once you enter a room, the camera is locked meaning the tiles should no longer flash. This will be reopened if this assumption is considered to be false and it is a bigger issue than we've made it to be.
