### ISSUE TITLE
Clipping through upside-down jumpthrus is the worst, most inconsistent tech I've ever seen in my life

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#114]
it adds nothing valuable to speedruns, it's just a run-killer. It's also more boring for tases than beating the screen normally. Patching it is literally just running an ahorn script on all maps.
Submitted by JaThePlayer

**Comment by maddie480** [comment]
> Patching it is literally just running an ahorn script on all maps.

No, fixing it is cherry-picking https://github.com/EverestAPI/SpringCollab2020/commit/0d5466bf230ee538729efbdbec4afa58f7ec6630

**Comment by Vexatos** [comment]
Now that a version with the clip is out (meaning TASers can just use an old version if they don't want to update), and considering the patches will have other breaking changes too, I see little reason to keep it. Instead of an ahorn script, it could easily be fixed directly in code.

**Comment by Vexatos** [comment]
Can be closed since https://github.com/EverestAPI/SpringCollab2020/commit/af83dd7b9930251b75d2921592bb0394cf2649e5.
