### ISSUE TITLE
Gem Garden jank

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#117]
In badeline screen, if you wait on the block as it goes off screen you will be warped to the other side of the block and regain your dash. https://cdn.discordapp.com/attachments/753301529422856192/754704091594358924/Celeste_2020-09-13_10-01-48_Trim.mp4
Submitted by Hydro0

**Comment by bissy-bissy-bissy** [comment]
DeathKontrol has said they don't mind if there is no fix for this is an easy fix cannot be discovered; if not, this will be closed.

**Comment by bissy-bissy-bissy** [comment]
An immediate fix was not discovered, so until then, this will be closed.
