### ISSUE TITLE
[Fishtank GM crash]

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#122]
[Koko crashes after backtracking from screen 4 to screen 3, Max480 said it's probably a watchtower in wall crash?]
Submitted by Cabob

**Comment by maddie480** [comment]
Certainly caused by a watchtower in an exit block in room 3. If you come from the right, the exit block appears right away, and triggers the watchtower-in-wall crash.

**Comment by maddie480** [comment]
Now duplicate of #128
