### ISSUE TITLE
Ancient Engine Wonky Camera

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#13]
In the last room, Ancient Engine has camera that lets you see up as you touch the berry, but when you get the berry there is no camera trigger to reset your camera. This makes your camera at ~-1.5 y, which makes you unable to see far down, and then you most likely plummet to your death.
Submitted by Bissy

**Comment by bissy-bissy-bissy** [comment]
aridai gave confirmation I could fix this.
