### ISSUE TITLE
Speedberry centered timer not centered

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#140]
in case its relevant, im playing on a 2560x1440 monitor in windowed mode with the window being 1920x1080 resolution (i kinda doubt this is relevant but since i havent seen this happen to anyone else yet i figured i might mention this) https://clips.twitch.tv/WildCleverPidgeonOSfrog
Submitted by Marlin

**Comment by maddie480** [comment]
Seems pretty broken to me, I'll check if I broke switching between modes mid-level by accident.

**Comment by maddie480** [comment]
Fixed in https://github.com/EverestAPI/CelesteCollabUtils2/commit/fce0023694a806cd390458feb374ab85e44300c0
