### ISSUE TITLE
theo barriers not working properly

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#149]
I reached flag 3 of beginner heartside and I'm told that I did it an unintended way due to the theo barrier not working. https://streamable.com/zxoc3x this is what I did. I have used debug in other maps in the collab, but not on this one if it matters (I saw the warning in Gamebanana).
Submitted by Projecteer

**Comment by LinjKarma** [comment]
i believe this was a bug in DJmaphelper that was fixed
