### ISSUE TITLE
Gold time on nyoom has over 5s of leniency

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#152]
Very generous for what's supposed to be a perfect run. Suggesting to move gold time to 0:55 and silver time to 1:17.5, keep bronze as is at 1:40
Submitted by ⚜ NeoKat ⚜

**Comment by NeoKat75** [comment]
**EDIT:** speedberries don't take decimals. Keep silver and bronze as is, only change gold to 0:55
