### ISSUE TITLE
camera issue in Dav's GM map

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#161]
https://imgur.com/a/NHrTHL1 going back from the berry route in the 2nd gameplay room has very awkward camera with Madeline being near the top of the screen and one of the spinners that can kill you practically being invisible
Submitted by Milk Thief 🍪

**Comment by ICookieCycloneI** [comment]
Another camera issue found in the room following that one: https://imgur.com/a/EgYoBz6
