### ISSUE TITLE
Hard crash during the elevator scene on Prologue

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#17]
Crash on Prologue without error log. Example log.txt from someone with the issue (might help to replicate): <https://cdn.discordapp.com/attachments/514006912115802113/753529840753180682/log.txt>
Might be a MonoKickstart-only issue? There already were such crashes in the past.
Submitted by max480

**Comment by maddie480** [comment]
I tried really hard to replicate this one (installing all the code mods mentioned in the log.txt to my Linux VM) and couldn't. Sounds like people having it solved it by blacklisting mods.

**Comment by maddie480** [comment]
Closing for now, might reopen if someone else reports it (it might just be another form of out of memory issue)
