### ISSUE TITLE
Crystal Enigma Kevin jank

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#183]
In the room that requires kevins to get a berry in Crystal Enigma, something really strange happened in Vesting's twitch stream where a kevin went inside of the other XD. twitch clip: https://clips.twitch.tv/RelentlessOpenLorisOptimizePrime
Submitted by Projecteer

**Comment by bissy-bissy-bissy** [comment]
Yeah this happens sometimes
