### ISSUE TITLE
binos in vanilla

### ISSUE THREAD

**Issue by ladrecha** [iamdadbod/SpringCollab2020Issues#187]
Hi guys, thanks for your work the map's amazing.

I believe you guys have tweaked the binos so that it doesn't let you skip spikes. I wanted to let you know that it also affects vanilla game and imo it shouldn't. For instance bino clip in Farewell is not doable while the mod is active.

Thanks again and have a nice day,
Hiken

**Comment by bissy-bissy-bissy** [comment]
Hey! I'm sorry, but I don't know how to fix this; as far as we know, we didn't fix bino spike skip specifically in the collab. If it's not doable while the mod is active, but it is doable while the mod is inactive, it may not be the mod but rather a dependency we use for the collab. Maybe you'll have more luck asking specific dependency creators?

Either way, it's worth investigating what's causing this. It shouldn't be the collab itself, but I'd like more information on this to fix this. My tag on discord in the official Celeste discord is ugh#0577, feel free to contact me there if you end up figuring out what's causing this.
- Bissy
