### ISSUE TITLE
Display End Screen option description

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#205]
Remove the "IL" from the description cause its also required for non IL submissions, since we still wanna see the collab version on the chapter complete screen
Submitted by Marlin

**Comment by maddie480** [comment]
Waiting for an answer on that, the collab version should show up regardless of that setting

**Comment by UltraMarlin** [comment]
Yeah youre right, my bad. I think people doing full hub runs should still have the option enabled anyway so they are able to submit the ILs they get but I guess we can expect people to be smart enough about that themselves
