### ISSUE TITLE
pause menu behavior

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#206]
sometimes when i open the game my pause menu looks like this and i do not know what happens. closing and reopening fixes it
Submitted by Lmjacks

**Comment by maddie480** [comment]
attached image

![image](https://cdn.discordapp.com/attachments/753487654435422228/756710133006073976/unknown.png)

**Comment by maddie480** [comment]
Waiting for more info, I also got it in the past but by playing back a TAS with the `console load` command (due to how the TAS tools load the debug save, the "Return to Map" button doesn't show up if you didn't beat Prologue on the debug save).

**Comment by maddie480** [comment]
Would be better to fall back to displaying "return to lobby" on the bottom of the pause menu, instead of the top

**Comment by maddie480** [comment]
Implemented by https://github.com/EverestAPI/CelesteCollabUtils2/commit/485b4382e80e320e7c58bbf808222b9898b9584e
