### ISSUE TITLE
Chapter Complete timing tweaks

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#208]
if speedrunning standard is to be by chapter complete, it's probably wise to patch out some instances where retrying resetting timer leads to beneficial timesaves (think core C heart door for ILs).  one particular example is that in blast processing, it's a fair bit faster to reach the end of the first screen, activate the last traffic block, and then retry, as this allows you to skip doing this with a reset timer.  unfortunately fixing this seems like a huge headache since every level needs to be investigated potentially.  alternative solutions would be to either live with it, or just restrict it as a whole for IL rules
Submitted by amber

**Comment by UltraMarlin** [comment]
Easy fix for all maps for this would be to disable timer reset on retrying. The randomizer does something like that. Would obviously make it so you cant quickly reset runs anymore in most maps if you mess up first room, so fixing the 1st rooms that have stuff that persists through death would be prefered (also from a level design perspective imo)

**Comment by maddie480** [comment]
Piece of code that does that in the randomizer: https://github.com/rhelmot/CelesteRandomizer/blob/master/Randomizer/Patches/mechanics.cs#L146

**Comment by maddie480** [comment]
We should be able to fix that by resetting session flags when the timer is reset.

**Comment by maddie480** [comment]
This solution has been implemented in https://github.com/EverestAPI/SpringCollab2020/commit/910500c245058191cad69c4444469d1f7002c779

Can confirm this turns back off levers in the intro room of Blast Processing if you die after activating it.
