### ISSUE TITLE
Ancient Engine Unplayable Cam

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#211]
In the last screen of Ancient Engine, when you go back to get the coin, when you fall back down you can't see anything because the cam is focusing all the way upward. It's very bad since you need to fall precisely in a gap, and it essentially makes that room unrunnable. It's the very last room of the map too
Submitted by Plush

**Comment by tcookiem** [comment]
Image: https://cdn.discordapp.com/attachments/753487654435422228/756827341564542976/unknown.png

**Comment by aridai-shi** [comment]
As the original mapper, I approve, do it.
