### ISSUE TITLE
level name display on end screens

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#212]
currently the end screens of the heart are mostly black screens with no easy way to tell what level was played if someone just posts a screenshot. Additionally having the name of the chapter displayed at the end would make verifying ILs a bit easier cause it will probably take a while until we learn all the names for ILs. Bottom middle of the screen could work for this as we require that part of the screen to be visible anyway because thats where the berry progress bar would show up normally.
Submitted by Marlin

**Comment by maddie480** [comment]
Should be addressed by https://github.com/EverestAPI/CelesteCollabUtils2/commit/b9db9b53ca929ec1ded4329ab953072873fe472d

Preview: 
![image](https://cdn.discordapp.com/attachments/532697531562590218/756866619623342150/unknown.png)

Waiting for feedback before closing, but should be good

**Comment by maddie480** [comment]
seems good, closing
