### ISSUE TITLE
grey out chapter timer when doing invalid stuff

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#213]
In vanilla, the chapter timer gets greyed out if you respawn at a golden berry spawn point, it would be nice if this was also the case in collab ILs
Submitted by Marlin

**Comment by maddie480** [comment]
Fixed in https://github.com/EverestAPI/CelesteCollabUtils2/commit/1f45383cd1a5d45c36b09d0e09c76eeee4d51eea
