### ISSUE TITLE
Berry sound upon file select

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#220]
I don't know if there's a collab correlation, but someone claimed beneath the video that it started once they downloaded the collab
https://discordapp.com/channels/403698615446536203/429775260108324865/757390318697054360
Submitted by Bissy

**Comment by maddie480** [comment]
... the simple fact of doing `strawberryCounter.Amount = someAmountOfBerries` emits a sound, actually, unless a flag is set. I got to check that

**Comment by maddie480** [comment]
Fixed by https://github.com/EverestAPI/CelesteCollabUtils2/commit/a419c61e0a91ba75837053160b864eddf9c390de
