### ISSUE TITLE
Tripeak Trail springs seem to be subpixel dependent

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#231]
depending on where the upper circled spring is hit (which cannot be controlled by the player), the jelly may or may not hit the spring afterward https://cdn.discordapp.com/attachments/702600073963372695/758072123179663430/unknown.png
Submitted by euni

**Comment by bissy-bissy-bissy** [comment]
This should be fixed with the new Tripeak Trail
