### ISSUE TITLE
Olden Tower Ruins

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#241]
saved and quit in the middle of it, downloaded and played another map on another file, when i came back the music wasnt playing and dream blocks were deactivated. idk what caused this, but the map was the weird 666 berry map
Submitted by dabba

**Comment by maddie480** [comment]
~~24x33 is quite cursed~~ but it doesn't seem to have anything to do with this. Some rooms have music set to `event:/SC2020_Dadbod_Octo` and others `event:/SC2020_DadBod_Octo`, and the correct is the first one. So the simple fact of saving & quitting in the second room then coming back makes the music go away.

Cannot replicate the dream block issue though.

**Comment by maddie480** [comment]
closing as duplicate of #272 and since I have no idea where the second one could come from.
