### ISSUE TITLE
extended variants not resetting correctly

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#242]
https://cdn.discordapp.com/attachments/754495709872521287/758567868601729034/Celeste_2020.09.23_-_23.54.33.04.DVR_Trim.mp4
if you console load into the GMHS, extended variants doesnt reset when you die
Submitted by Vamp

**Comment by maddie480** [comment]
Should be fixed in Extended Variants 0.16.2
