### ISSUE TITLE
Add an option to disable speedberry timer

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#244]
Sometimes in Claustrophobia the speedberry timer can obscure Madeline entirely, and is a problem regardless of whether you put it in top middle/top left. An option to disable the onscreen timer entirely or to replace the in game timer with it might be helpful so that it obscures less of the player's view in some cases.
Submitted by dog

**Comment by maddie480** [comment]
This can be done as a third "speed berry timer position"

**Comment by maddie480** [comment]
Done in https://github.com/EverestAPI/CelesteCollabUtils2/commit/a0b9f59e3d8765175f63d1e820a6a8adb7501c72
