### ISSUE TITLE
Incorrect music credits for Ultra Difficult

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#246]
![image](https://cdn.discordapp.com/attachments/445236692136230943/758717234306351135/IMG_20200924_175105.jpg)
Should be "Music: Frozen Hot Sauce (by Lifeformed)" or just "Music: Lifeformed"
Submitted by max480

**Comment by maddie480** [comment]
Adding the song name allows for it to be found more easily, so preferably go for "Music: Frozen Hot Sauce (by Lifeformed)"
