### ISSUE TITLE
jelly machine issue in dog's GM map (Aquatic Underground)

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#250]
the second jelly machine in doggo_03 (vertical tunnel with current + springs you throw jelly into) sometimes doesn't work. If you throw the jelly low enough, it hits the wall below the first set of springs, then dodges the second spring and gets stuck permanently on the ceiling of the tunnel, breaking the next section
Submitted by Bigkahuna

**Comment by bissy-bissy-bissy** [comment]
Should be fixed in the next update, this was supposed to be fixed a lot earlier but the update wasn't pushed, sorry about that.
