### ISSUE TITLE
It is still possible to end up on one of the hidden level sets

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#251]
For that, you have to get on the collab map, restart chapter, and force close the game (alt-f4). Upon reloading the save file, you have the collab map selected in the overworld
Submitted by max480

**Comment by maddie480** [comment]
Fixed by https://github.com/EverestAPI/CelesteCollabUtils2/commit/3114fb90c56c52c34662e1b1b0e550f1c0f73463
