### ISSUE TITLE
Cycle timing in Electric Exuberance

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#253]
after some discussion with others who've played the map casually i think the setup for timing the cycle (literally just hold forward) could/should be made more clear - if you try to hyper or do any other movement besides just hold forward while waiting for the cycle to be cleared, this level is very very frustrating.  i wasn't the only person who had this problem, and personally this was the least fun expert level for me (even counting cycle madness) and giving it another playthrough after being told to just hold forward made it much more pleasant, as otherwise you get to blindly race against cycles for 8 or so seconds before they suddenly tick over 3 seconds early despite you seemingly not making any mistakes.  there's background images that try to tell you this, but i think something this specific should probably just be explicitly stated somehow (i would rather be told exactly in a dialog box how this worked rather than the alternative of not knowing and just having to deal with getting fucked over quite often, but there's probably a more creative but direct way to inform the player)
Submitted by amber

**Comment by bissy-bissy-bissy** [comment]
CANADIAN does not want this change to go through, so it won't be resolved
