### ISSUE TITLE
Water and Ice softlock #1

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#256]
Retrying after collecting the first key in `r-2` and before getting bubbled spawns you back at the section but with the key. The key bubbling you is the only way out so you're softlocked. Can be fixed by adding a change respawn trigger on top of the key that sets your respawn to where it normally is after being bubbled. https://cdn.discordapp.com/attachments/663493647370813461/759023846794854421/water_and_ice_softlock_1.mp4
Submitted by The_Cookie_Monster

**Comment by tcookiem** [comment]
Similar to https://github.com/iamdadbod/SpringCollab2020Issues/issues/257
