### ISSUE TITLE
Water and Ice softlock #2

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#257]
After collecting the first key in `r-2`, being bubbled, and setting a certain respawn point you can be softlocked. Steps to reproduce:
- Collect the key and be bubbled over
- Go down to the platform below (this sets your respawn point)
- Without going back to the platform above, go across to the platform with the core switch
- Hit the core switch
- Die without entering the change respawn trigger that sets your respawn to there
This results in you spawning back on the bottom platform but in hot core mode. You are stuck on that side as the only way out normally is to be bubbled by the key. Can be fixed by extending the change respawn trigger next to the core switch to cover it.
 https://cdn.discordapp.com/attachments/663493647370813461/759023913090416710/water_and_ice_softlock_2.mp4
Submitted by The_Cookie_Monster

**Comment by tcookiem** [comment]
Similar to https://github.com/iamdadbod/SpringCollab2020Issues/issues/256
