### ISSUE TITLE
lethargicdoggo expert overly precise nonsense

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#265]
this updash at the end of screen 3 is literally frame perfect - tested in TAS to confirm.  the alternative strat is really clunky (double jump left out of dreamblock to kill speed) and unintuitive, this seems like a pretty clear oversight since it's right near the end of the screen.  https://i.gyazo.com/a598fcd9a488e2cd26f55fbefafe3c2e.png updash in question
Submitted by amber

**Comment by bissy-bissy-bissy** [comment]
LethargicDoggo said they won't be looking into this, sorry
