### ISSUE TITLE
savestate speedberry crash

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#267]
Savestating while holding a speedberry seems to crash the game https://canary.discordapp.com/channels/403698615446536203/407934733595705344/760238521536479322. Not sure when this happens, but you can ask the person who noticed it
Submitted by Oppen_heimer

**Comment by maddie480** [comment]
should be fixed by https://github.com/EverestAPI/CelesteCollabUtils2/commit/933ee48138324d0c82e9f4e3881f8a5ded09e496
