### ISSUE TITLE
EHS flag 1 OOB

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#268]
https://media.discordapp.net/attachments/713422285381435402/760298551770218517/seeoob.PNG?width=1048&height=577
https://media.discordapp.net/attachments/713422285381435402/760298673006444605/camera.PNG?width=1067&height=577
Submitted by tobyaaa

**Comment by tobyaaaa** [comment]
in retrospect I guess the first picture could use some clarification; if you dash up as far upleft as you can get, you can see  a bit out of bounds on the top right of the camera
