### ISSUE TITLE
Olden Tower Ruins music won't reinitiate

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#272]
Music in the Olden Tower Ruins is not reinitiated outside of the spawn room, if the map is reloaded by means such as Save and Quit
Submitted by Scroogle

**Comment by maddie480** [comment]
Some rooms have music set to `event:/SC2020_Dadbod_Octo` and others `event:/SC2020_DadBod_Octo`, and the correct is the first one. So the simple fact of saving & quitting in the second room then coming back makes the music go away.
