### ISSUE TITLE
KoKoDoKo? crash on room transition

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#277]
i transitioned from fishtank_03 to fishtank_04, then attempted to go back before the exit block spawned. my game crashed with the attached error. i then reopened the map through the lobby and it had wiped all my progress. i tried to debug back to the end of fishtank_03 to try again and it crashed + wiped my progress again.
Submitted by Bigkahuna

**Comment by maddie480** [comment]
Duplicate of #128
