### ISSUE TITLE
Crumbling Castle - "tunnel of shame" can be seen as rude to the player

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#288]
seriously all this text does is mock the player if they don't get a berry? i mean i get that unfun and frustrating is the theme of the map but c'mon seriously? https://cdn.discordapp.com/attachments/702600073963372695/758870325239742527/unknown.png
Submitted by euni

**Comment by bissy-bissy-bissy** [comment]
This isn't happening since it wasn't interpreted to be rude, sorry
