### ISSUE TITLE
silver berry in blast processing

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#298]
doesn't register in journal https://cdn.discordapp.com/attachments/753487654435422228/764279551365873674/unknown.png https://cdn.discordapp.com/attachments/753487654435422228/764279617828945960/unknown.png found by verdal
Submitted by tofu

**Comment by maddie480** [comment]
The journal shows a dot there likely because spawning from the golden berry respawn point doesn't count as a "full run", and if you didn't _ever_ do a single run on that save, a dot is shown here.

**Comment by maddie480** [comment]
Should be fixed by https://github.com/EverestAPI/CelesteCollabUtils2/commit/d9e70141f02d7a565c5aaf5a6be3c23cbb6c4704
