### ISSUE TITLE
Flag 1 of Intermediate Heart-side, sideways ice, not sideways lava

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#301]
What is supposed to be sideways lava here (at the Madeline Jones and the Temple of Zoom portion of Flag 1 Intermediate Heart-Side) registers as sideways ice, despite entering the section with the hot mode toggled, as indicated by the top/bottom sandwich lava
Submitted by RamenTwig

**Comment by bissy-bissy-bissy** [comment]
I couldn't recreate this so I don't know how to fix it, sorry; if this issue was due to debugging that's most likely the answer
