### ISSUE TITLE
Camera transition breaks viewfinder in Rhythm Realm

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#308]
Entering the viewfinder shown in this screenshot https://i.imgur.com/48UXgQo.png from the left, during a camera transition, prevents control of the camera via viewfinder. Note lack of directional arrows on the frame.
Submitted by Scroogle

**Comment by maddie480** [comment]
![image](https://i.imgur.com/48UXgQo.png)
