### ISSUE TITLE
Space Garden (dozing advanced) bad screen transition w/ assist mode

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#328]
going downwards in dozing_06 with assist mode results in an unintended screen transition which causes the camera to snap down due to the badeline camera lock, causing madeline to get stuck in a wall https://streamable.com/4mj1r4
Submitted by amber

**Comment by bissy-bissy-bissy** [comment]
Changing this would require significant effort and potentially negatively impact the room's camera for a fix that is irrelevant; won't get fixed, sorry
