### ISSUE TITLE
Weird Standing Spot in Major Malfunction

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#337]
You can stand here in Major Malfunction, but you die when you duck. ![image](https://cdn.discordapp.com/attachments/753487654435422228/776091999882444870/Screen_Shot_2020-11-11_at_8.30.44_AM.png)
Submitted by DanTKO | CEO Of Haikus

**Comment by bissy-bissy-bissy** [comment]
Will be looked into, minemah is ok with this change
