### ISSUE TITLE
Subterranean Exploration

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#349]
pleeeeeease add binos (watchtowers) in every room thank you. also i personally had problems with the visual contrast (black and red dust bunnies on reddish-brown background) but...i dunno how to really fix that. it'd be nice if the background was more light brown with no red, or if the dust bunnies were light brown spinners instead or something. but that's less important than the binos
Submitted by metagloria

**Comment by bissy-bissy-bissy** [comment]
deskilln approves of this change;

"I don't really have easy access to my own map rn but i think it would be fixed by changing bgs/09/bg2's Colour property to AAAAAA or something like that"

Will only add a bino to room 3
