### ISSUE TITLE
coin inconsistency in Electric Exuberance

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#358]
the coin shown in attached screenshot is the wrong type, it's supposed to be the triangle one. https://cdn.discordapp.com/attachments/753487654435422228/788788140940853269/Screen_Shot_2020-12-16_at_10.19.55_AM.png
Submitted by DiranOrange

**Comment by bissy-bissy-bissy** [comment]
Approved for change
