### ISSUE TITLE
Flag Checkpoint not working as intended in Another Summit

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#362]
Dying on the left of the marked spike doesn't send you back to Flag 3 checkpoint. Instead, it spawns you next to Flag 2 checkpoint.
Submitted by Marki

**Comment by marki331** [comment]
The Screenshot I wanted to provide oopsie
https://media.discordapp.net/attachments/753487654435422228/789987358014701608/unknown.png?width=888&height=499

**Comment by bissy-bissy-bissy** [comment]
Silverstar approved this
