### ISSUE TITLE
temporal tower berry collect area

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#371]
(note: <@320725762300837890>  found this bug and i was just reporting it) berry collect area seems to be bugged, probably has to do with platforms not being considered "safe ground" (skip to 0:40 in this video) https://cdn.discordapp.com/attachments/666337196952780810/792782606541520896/Sky_Temple.mp4
Submitted by flash | CEO of typos

**Comment by xaviershrier** [comment]
This is a result of a berry collection blocker to prevent cheese of the second berry. As a compromise, I've made then entire watchtower area free of said blockers, so it's less intuitive for people who want to cheese it, while properly allowing collection of the first berry.
