### ISSUE TITLE
Starlit Grotto pufferfish doesnt get moved properly

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#374]
in the first gameplay room the pufferfish doesnt get moved up enough to complete the room - no other mods than SC2020 (and dependencies) are loaded, everest is current beta (2673), celeste is on 1.3.3.18. I cant test on non-beta celeste because of unrelated controller issues
Submitted by Lollyde

**Comment by Lollyde** [comment]
![image](https://user-images.githubusercontent.com/11347524/109847101-1ca88980-7c4f-11eb-94eb-a64f209eb4c1.png)

**Comment by xaviershrier** [comment]
No longer reproducible on latest Celeste (1.4.0.0) and Everest (3205). Seems to only occur if you manage to skip intended gameplay or otherwise complete the room in an unintended way, especially without bouncing the puffer into the spring before sending it upwards.
