### ISSUE TITLE
Game Crashes in Heart Room Of Ligament

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#382]
I recently updated to 1.4 and now using Olympus on a mac. I just played ligament for the first time yesterday and the game crashed when I entered the heart room. I've narrowed it down to something to do with the DJMapHelper/flingBirdReversed entity. When I delete it from the room, I no longer get crashes.
Submitted by MindfulOfTacos

**Comment by maddie480** [comment]
Issue with Fling Bird Reversed in DJ Map Helper, fixed in https://github.com/DemoJameson/CelesteDJMapHelper/commit/3fdf76803e91db6e2317ea893b207ba0c5532f18
