### ISSUE TITLE
bypass jelly barrier in toxic sewers intro

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#389]
with a well-timed updiag dash into the jelly, it is possible to carry it through the ceiling over the jelly barrier. allows you to much more easily collect the berry in the first room
Submitted by DiranOrange

**Comment by oinkymoo** [comment]
forgot to include image. https://discord.com/channels/663475651793125398/753487654435422228/859805759630082099
