### ISSUE TITLE
JaThePlayer's Death Desyncs

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#54]
3. the clone regains control after death before the player does--It just doesn't have a respawn animation--, so you can desync the clone and the player quite easily, if you immediately try to dash into a bubble, say, just after respawning
Submitted by Bissy

**Comment by Cruor** [comment]
Noted as a Pandora's Box bug/issue. Closing this issue when it is fixed in Pandora's Box.

**Comment by Cruor** [comment]
Fixed in Pandora's Box 1.0.24.
