### ISSUE TITLE
Dashes in dream blocks do not lag

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#56]
In Space Jam Fever Dream, dashing mid-dream block does not lag the game, making it very easy to misinput dashes
Submitted by euni

**Comment by Cruor** [comment]
Noted as a Pandora's Box bug/issue. Closing this issue when it is fixed in Pandora's Box.

**Comment by Cruor** [comment]
Fixed in Pandora's Box 1.0.24.
