### ISSUE TITLE
Level select screen appearing for sublevels

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#59]
Saving in a level then returning to titlescreen without saving will glitch the level select window: https://media.discordapp.net/attachments/702600073963372695/754031623812677823/unknown.png?width=1190&height=671
Submitted by euni

**Comment by maddie480** [comment]
I still don't get what "saving in a level then returning to titlescreen without saving" means exactly, but developing a fallback for that kind of situation (including Ctrl-teleporting) would be nice

**Comment by maddie480** [comment]
Solved in https://github.com/EverestAPI/CelesteCollabUtils2/commit/1e42141d03641dcdd3c1d51d496eda826e60d3c1
