### ISSUE TITLE
Crash with sideways lava and speedberry

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#61]
https://clips.twitch.tv/SmallSassyLeopardTBCheesePull  https://pastebin.com/zne0zNaK
Submitted by euni

**Comment by maddie480** [comment]
Fixed in https://github.com/EverestAPI/SpringCollab2020/commit/1c8fb2b487b14a4620dd5ab30cf5e1a6f0dada99
