### ISSUE TITLE
Journal Lowest Death Count

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#75]
Map: Ultra Difficult. Was going for speed berry attempts and, after a run with deaths, the lowest deaths in the journal said 0.<http://jack-frost.is-pretty.cool/3L7Qx5L.png>
When I looked at it before, it was at 76. I did not use debug in the map between the times of it reading 76 and it reading 0.
Submitted by Yoshi

**Comment by maddie480** [comment]
Seems like collecting the berry flips the "Grabbed Golden" flag... and that attribute forces the best death count to be saved as 0.

Actually... this Grabbed Golden also causes issues... in vanilla. I grabbed the golden, save & quit, then completed the level with 32 deaths, and my journal now says my PB is 0 deaths even though it was 22 before. Off to #bug_reports I go!

**Comment by maddie480** [comment]
Setting the "grabbed golden" flag with speed berries was fixed in https://github.com/EverestAPI/CelesteCollabUtils2/commit/7f5dba6f40703f3b8c11517a9f24d7e1aa485a46.
