### ISSUE TITLE
Berry Counter Being Weird in Beginner Maps

### ISSUE THREAD

**Issue by bissy-bissy-bissy** [iamdadbod/SpringCollab2020Issues#8]
Only the first berry in Blast Processing is in the berry counter in the pause menu apparently
This is also apparent in Badeline Block Belt, which only has 2 berries show up

**Comment by maddie480** [comment]
This was a berry order assignment issue (berries being ordered 1/2/3 instead of 0/1/2). Fixed in #update_dump
