### ISSUE TITLE
Other Gym Entrances in Gyms

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#80]
Maybe gyms should have all other gym entrances available at the start? That way if you don't know tech in previous gyms, you can easily check without switching to other lobbies? Or would this cause problems?

This came out when someone was in advanced and didn't know how to fast bubble, and the gym didn't help them as fast bubbling is only taught in beginner.
Submitted by Bissy

**Comment by bissy-bissy-bissy** [comment]
We decided not to do this due to the potential confusion that may come out of multiple gym entrances.
