### ISSUE TITLE
Lighting Options should be in save data

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#82]
In maps with in-level graphics options, like nyoom, the graphics choice should be included somewhere in save data. Otherwise, in full-hub runs, it will lose time to pick a preferred option.
Submitted by euni

**Comment by maddie480** [comment]
Closed by https://github.com/EverestAPI/SpringCollab2020/commit/14754c998003e88cb520ed107e0f8a263786d35f
