### ISSUE TITLE
SilverStar Intermediate: +1 refills aren't different enough from vanilla refills

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#83]
Vanilla refills are green, +1 refills are bluish green. Some people reported that seeing the difference between both is quite hard
Submitted by max480

**Comment by maddie480** [comment]
Reopening because it's not applied to the map yet

**Comment by bissy-bissy-bissy** [comment]
Closed since it should be applied to the map now
