### ISSUE TITLE
Unfair Speed berry deaths

### ISSUE THREAD

**Issue by BLimmie** [iamdadbod/SpringCollab2020Issues#89]
when speed berries are above death and collected for the first time, the dialogue stops you in mid air and kills you
Submitted by Thegur90

**Comment by bissy-bissy-bissy** [comment]
This has been decided to be fixed in case-by-case for maps rather than fixing it as a whole. Fixed in Thegur90's advanced map, Booster in Orbit; will be fixed in other maps when found

**Comment by bissy-bissy-bissy** [comment]
This has also been fixed in itsabrody's beginner map and BeefyUncle's advanced map. More cases will be looked at if necessary.

**Comment by xaviershrier** [comment]
Closed as this was addressed case by case, as mentioned above.
